- README.md
- observer/obs-electron/README.md
- survey/surv-cutter/package-lock.json
Updated Cryptiles to 4.1.2 in surv-cutter
Updating README to provide instructions for those who just want to download and run the application
> Updating README to provide instructions for those who just want to download and run

- fram-modules/README.md
- fram-modules/src/app/screens/home/home.component.html
- fram-modules/src/app/screens/home/home.component.ts
- fram-modules/tsconfig.json
Updated README.md with "paths" method (instead of npm link, which is a little flaky on Windows.)
> Add fram-models library to fram-modules

- fram-modules/angular.json
Should fix our local Jenkins build.
> fram-modules: Add fram-models to angular.json

- observer/obs-electron/package.json
- observer/obs-electron/src/app/app-routing.module.ts
Testing router download link (dev env only)
> obs-electron web: Add download to router (dev env test)

- survey/surv-cutter/package-lock.json
- survey/surv-cutter/package.json
Fix remaining project dependency
> Apply npm audit fix

- bn-modules/projects/bn-auth/src/lib/auth.service.ts
- observer/obs-electron/src-electron/electron-main.js
- observer/obs-electron/src/app/_services/dbConfig.SAMPLE.json
- observer/obs-electron/src/app/app.module.ts
- observer/obs-electron/src/app/header-toolbar/header-toolbar.component.ts
- observer/obs-electron/src/app/screens/login/login.component.html
Simplify dbConfig to only include an authURL,
Add optional injectable AuthServiceConfig to AuthService (bn-auth)
See obs-electron for example implementation
> Fix obs-electron login screen, default authURL

- apps/dev-auth-server/package.json
- apps/example/package.json
- apps/obs-wcgop-optecs/package.json
- apps/obs-wcgop-optecs/src/layouts/Default.vue
- apps/obs-wcgop-optecs/src/views/About.vue
- docs/dev-notes/quasar.md
- docs/dev-notes/useful-links.md
- libs/bn-auth/package.json
- libs/bn-models/index.ts
- libs/bn-models/models/base/base.ts
- libs/bn-models/models/base/haul.ts
- libs/bn-models/models/index.ts
- libs/bn-models/package.json
- yarn.lock
Needed a place to put development notes, configuration, etc
> Add docs/dev-notes

- apps/obs-wcgop-optecs/src/views/Hauls.vue
- apps/obs-wcgop-optecs/src/views/Trips.vue
- libs/bn-common/src/components/BoatnetHauls.vue
- libs/bn-common/src/components/BoatnetTrips.vue
- libs/bn-common/src/models/BoatnetHaulsSettings.ts
- libs/bn-common/src/models/BoatnetTripsSettings.ts
Moved columns and data out of BoatnetHauls and BoatnetTrips components. Completes #208
> Refactor BoatnetTrips, BoatnetHauls shared components

- apps/obs-wcgop-optecs/src/views/Login.vue
Made the following changes: 
Centered Input fields
Disabled login button until both fields contain text
Added spinner to login button that displays when someone is in the process of logging in 
Added visibility button to password input field
Moved error message to the top
> Styling for login screen

- apps/obs-web/src/views/Debriefer.vue
@Mak-NOAA I did a few things to help you get started:
- converted your `columns` and `data` fields into the typescript class style, 
- added the necessary types so typescript compiles
- fixed TSLint issues using VSC's format document command
> Fix typescript errors and tslint warnings/errors

- apps/obs-wcgop-optecs/src/views/TripDetails.vue
- libs/bn-common/src/components/BoatnetKeyboard.vue
- libs/bn-models/models/_common/measurement.ts
- libs/bn-models/models/_lookups/person.ts
- libs/bn-models/models/_lookups/vessel.ts
Fixing this issue https://github.com/nwfsc-fram/boatnet/issues/318
> Fixing keyboard interaction with q-select

- libs/bn-models/models/_lookups/catch-content.ts
- libs/bn-models/models/_lookups/catch-grouping.ts
- libs/bn-models/models/_lookups/debris.ts
- libs/bn-models/models/_lookups/index.ts
- libs/bn-models/models/_lookups/taxonomy.ts
Added the taxonomy, catch-content, catch-grouping, and debris models per our Taxonomy discussion on 5/2/2019
> Added taxonomy, catch-content, and catch-grouping

- apps/obs-wcgop-optecs/src/main.ts
- apps/obs-wcgop-optecs/src/views/TripDetails.vue
- libs/bn-common/src/components/BoatnetLicenses.vue
- libs/bn-common/src/main.ts
https://github.com/nwfsc-fram/boatnet/issues/220
> Trip Details fixes #220

- apps/obs-web/src/views/Debriefer.vue
@sethgerou-noaa  I am trying to retrieve 1 column (Fishery) to display in a qasar table but nothing is being populated on the table. I do see on the console.log that data is being retrieved. Any idea?
> Retrieve 1 column from couchdb

- apps/obs-web/src/views/Debriefer.vue
Adding additional columns on the trips page
> Added more columns to the trips table

- apps/obs-wcgop-optecs/src/_store/wcgop-app-state.module.ts
- apps/obs-wcgop-optecs/src/components/OptecsBreadcrumbs.vue
- apps/obs-wcgop-optecs/src/router.ts
- apps/obs-wcgop-optecs/src/views/TripDetails.vue
- apps/obs-wcgop-optecs/src/views/Trips.vue
- libs/bn-common/src/components/BoatnetDatetime.vue
- libs/bn-common/src/components/BoatnetTrips.vue
- libs/bn-common/src/main.ts
Added save functionality to trip details page. 
https://github.com/nwfsc-fram/boatnet/issues/220
https://github.com/nwfsc-fram/boatnet/issues/25
https://github.com/nwfsc-fram/boatnet/issues/219
> Trip details fixes for issues #220, 20, 291

- apps/dev-auth-server/package.json
- apps/dev-auth-server/src/main.ts
- apps/obs-wcgop-optecs/src/_store/tally.module.ts
- apps/obs-wcgop-optecs/src/views/Login.vue
+ minor tally updates.
Doing this to verify that downgrading Quasar version will fix issue with q-select.
> Tally: Add quasar version# to Login

- apps/dev-auth-server/package.json
- apps/example/package.json
- apps/obs-wcgop-optecs/package.json
- apps/obs-web/package.json
- apps/surv-hake-wetlab/package.json
- libs/bn-auth/package.json
- libs/bn-common/package.json
- libs/bn-couch/package.json
- libs/bn-models/package.json
- libs/bn-util/package.json
Pending my bug here:
https://github.com/quasarframework/quasar/issues/4114
> Rollback Quasar to v1.1.0-beta.16

- apps/obs-web/src/views/Debriefer.vue
Add the remaining columns for the debriefer trip page
> Add remaining of the debriefer trip page columns

- apps/dev-auth-server/package.json
- apps/example/package.json
- apps/obs-wcgop-optecs/package.json
- apps/obs-wcgop-optecs/src/_store/tally.module.ts
- apps/obs-wcgop-optecs/src/_store/types/tally.ts
- apps/obs-wcgop-optecs/src/components/tally/TallyAddNamedSpeciesDialog.vue
- apps/obs-wcgop-optecs/src/components/tally/TallyBtn.vue
- apps/obs-wcgop-optecs/src/components/tally/TallyLayoutControls.vue
- apps/obs-wcgop-optecs/src/views/Tally.vue
- apps/obs-web/package.json
- apps/surv-hake-wetlab/package.json
- libs/bn-auth/package.json
- libs/bn-common/package.json
- libs/bn-couch/package.json
- libs/bn-models/package.json
- libs/bn-util/package.json
Rolls all apps forward to beta.23 of Quasar v1.
Addresses #358 (changes to q-select autocomplete.)
> Tally - Move buttons, fix autocomplete

- apps/obs-wcgop-optecs/src/_store/tally.module.ts
- apps/obs-wcgop-optecs/src/_store/types/tally.ts
- apps/obs-wcgop-optecs/src/components/tally/TallyBtn.vue
- apps/obs-wcgop-optecs/src/components/tally/TallyLayoutControls.vue
- apps/obs-wcgop-optecs/src/views/Tally.vue
- apps/obs-wcgop-optecs/src/views/TripDetails.vue
Addresses #358 for Trip Details
> Fix Trip Details q-select (new quasar version)

- apps/obs-wcgop-optecs/src/_store/tally.module.ts
- apps/obs-wcgop-optecs/src/_store/types/tally.ts
- apps/obs-wcgop-optecs/src/components/tally/TallyBtn.vue
- apps/obs-wcgop-optecs/src/views/Tally.vue
> Track last +/- and display icon on button

- apps/obs-wcgop-optecs/src/_store/tally.module.ts
- apps/obs-wcgop-optecs/src/views/Tally.vue
> Tally: more logic for removing TEMP buttons

- apps/obs-wcgop-optecs/src/_store/types/tally.ts
- apps/obs-wcgop-optecs/src/views/Tally.vue
> Fix add named species

- apps/obs-wcgop-optecs/src/_store/types/types.ts
- apps/obs-wcgop-optecs/src/_store/wcgop-app-state.module.ts
- apps/obs-wcgop-optecs/src/layouts/Default.vue
- apps/obs-wcgop-optecs/src/views/TripDetails.vue
- apps/obs-wcgop-optecs/src/views/Trips.vue
- libs/bn-common/src/components/BoatnetDate.vue
- libs/bn-common/src/components/BoatnetDatetime.vue
- libs/bn-common/src/components/BoatnetFishTickets.vue
Modified sidebar so users can view it either in expanded mode or mini mode. 
https://github.com/nwfsc-fram/boatnet/issues/402
Also hooked trip details to load from the database.
> Expanding and collapsing sidebar to show minified version and loading trip details from the database

- libs/bn-models/models/_base/base-specimen.ts
- libs/bn-models/models/_common/biostructure.ts
- libs/bn-models/models/_common/index.ts
- libs/bn-models/models/_common/lineal-measurement.ts
- libs/bn-models/models/_lookups/index.ts
- libs/bn-models/models/_lookups/protocol.ts
- libs/bn-models/models/hakesurvey/hake-survey-basket.ts
- libs/bn-models/models/hakesurvey/hake-survey-catch-species.ts
- libs/bn-models/models/hakesurvey/hake-survey-catch.ts
- libs/bn-models/models/hakesurvey/hake-survey-haul.ts
- libs/bn-models/models/hakesurvey/hake-survey-specimen.ts
- libs/bn-models/models/hakesurvey/index.ts
updates from session with Alicia and Beth.
> Hake Survey model updates

- libs/bn-common/src/components/BoatnetTable.vue
- libs/bn-models/models/_base/base-specimen.ts
- libs/bn-models/models/_common/brd-configuration.ts
- libs/bn-models/models/_common/lineal-measurement.ts
- libs/bn-models/models/_lookups/brd-lookups.ts
- libs/bn-models/models/_lookups/catch-content.ts
- libs/bn-models/models/_lookups/protocol.ts
Fix up latest updates that had various ts-lint warnings and trailing whitespace errors
> Fix ts-lint warnings and trailing whitespace

- apps/obs-wcgop-optecs/src/_store/tally.module.ts
- apps/obs-wcgop-optecs/src/_store/types/tally.ts
- apps/obs-wcgop-optecs/src/components/tally/TallyAllTalliesControls.vue
- apps/obs-wcgop-optecs/src/components/tally/TallyBtn.vue
- apps/obs-wcgop-optecs/src/components/tally/TallyControlBtn.vue
- apps/obs-wcgop-optecs/src/views/Tally.vue
> All Tallies For...  functionality

- apps/obs-wcgop-optecs/src/components/tally/TallyAllTalliesControls.vue
- apps/obs-wcgop-optecs/src/views/Tally.vue
- libs/bn-common/src/components/BoatnetAddSpeciesDialog.vue
- libs/bn-common/src/main.ts
> Move BoatnetAddSpeciesDialog to bn-common

- apps/obs-web/src/views/Debriefer.vue
@sethgerou-noaa  I tried to add a multi select dropdown (https://v1.quasar-framework.org/vue-components/select#The-model) to allow the user to control visible columns but somehow the toggle switches disappeared and the select list doesn't even show. I don't even know how to debug why they disappeared, any advice?
> adding a multi select dropdown for visible columns

- apps/obs-web/src/views/Debriefer.vue
- libs/bn-models/models/wcgop/ots-target.ts
@Mak-NOAA @toddhay-NOAA 
Todd and I were chatting about the look of the select, and thought it looked a little rough with all options selected, so I looked into disabling showing the selected options, and adding icons to selected options in the dropdown.
> obs-web: debriefer column select styling

- apps/example/src/main.ts
- apps/obs-web/src/main.ts
- apps/obs-web/src/views/Debriefer.vue
@sethgerou-noaa I'm attempting to add https://quasar.dev/vue-components/tab-panels#Example--With-QTabs to the debriefing page however I'm getting the following error:
```
vue.runtime.esm.js?8846:619 [Vue warn]: Unknown custom element: <q-tabs> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
found in
```
```
[Vue warn]: Unknown custom element: <q-tab> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`
```
```
[Vue warn]: Unknown custom element: <q-separator> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
found in
```
Any thoughts on how the registering works? I thought I did it right with main.ts
> Adding Quasar Tab Panels w/ registering error

- libs/bn-models/models/_common/fishing-location.ts
@NickShafferNOAA a few suggestions:
* looks like your git is misconfigured, this was committed as "Nicholas.Shaffer" instead of NickShafferNOAA.
* various ts-lint errors and trailing whitespace, which prevents me from committing via the pre-commit hook, please configure that and use Vetur/ VSC to avoid pushing stuff with ts-lint warnings, I usually just use auto-format to make that easy (shift-alt-f)
* please commit to a branch instead of directly to master as described in CONTRIBUTING.md
> Fix various ts-lint and trailing whitespace errors

- apps/obs-wcgop-optecs/package.json
- apps/obs-wcgop-optecs/src/_store/index.ts
- apps/obs-wcgop-optecs/src/_store/pdf.module.ts
- apps/obs-wcgop-optecs/src/_store/tally.module.ts
- apps/obs-wcgop-optecs/src/_store/types/types.ts
- apps/obs-wcgop-optecs/src/components/tally/TallyControls.vue
- apps/obs-wcgop-optecs/src/components/tally/TallyHistoryDialog.vue
- apps/obs-wcgop-optecs/src/components/tally/TallyPDFOptionsDialog.vue
- apps/obs-wcgop-optecs/src/shims-vue.d.ts
- apps/obs-wcgop-optecs/src/views/Hauls.vue
- apps/obs-wcgop-optecs/src/views/Tally.vue
- libs/bn-util/index.ts
> PDF Generation

- apps/obs-web/src/views/Debriefer.vue
Fixes the following:
```
WARNING in C:/git/boatnet/apps/obs-web/src/views/Debriefer.vue
269:61 missing whitespace
267 | private WcgopOperations: WcgopOperation[] = [];
268 | private pagination = {rowsPerPage: 50};
> 269 | private visibleTripColumns = ['key', 'tripStatus', 'vessel','program','departurePort','departureDate','returnPort','returnDate'];
|                                                             ^
270 | private visibleOperationColumns = ['tripKey', 'operationNum','position','location','observerTotalCatch','gearType','gearPerformance','targetStrategy',
271 |   'isEfpUsed','calWeight','fit','isGearLost','isDataQualityPassing','beaufortValue','isDeterrentUsed','excluderType','avgSoakTime',
272 |   'totalHooks','totalHooksLost','totalGearSegments','gearSegmentsLost','hooksSample …
```
> Fix debriefer warnings

- apps/obs-wcgop-optecs/src/views/Trips.vue
@melinashak-noaa Fixed an edge case for very first trip # created (tripNum was uninitialized so couldn't auto-increment.)
> Fix trip # for first trip

- apps/obs-wcgop-optecs/src/views/Hauls.vue
- libs/bn-common/src/components/BoatnetButtonToggle.vue
- libs/bn-common/src/components/BoatnetLicenses.vue
- libs/bn-common/src/components/BoatnetLocations.vue
Haul Locations fix: https://github.com/nwfsc-fram/boatnet/issues/482
Combine button bar: https://github.com/nwfsc-fram/boatnet/issues/473
Delete dialog for permits: https://github.com/nwfsc-fram/boatnet/issues/472
> fixing boatnet issues #482, 473, 472

- libs/bn-common/src/components/BoatnetKeyboard.vue
https://github.com/nwfsc-fram/boatnet/issues/470
> shrinking keyboard width for num keypad

- apps/obs-web/src/views/Debriefer.vue
@sethgerou-noaa @toddhay-NOAA @wsmith-nwfsc any suggestions for null checking db fields that are null other than using my own homemade nullcheck functions? (see nullValueCheck and nullDescriptionCheck)
doing ".description" or ".value" was throwing undefined error on items that didn't have a value from the db.
@NickShafferNOAA FYI
> Debriefer hauls page

- apps/obs-wcgop-optecs/src/App.vue
- apps/obs-wcgop-optecs/src/_store/index.ts
https://github.com/nwfsc-fram/boatnet/issues/498
> Fixing numpad to close when a text field is no longer selected or the page is refreshed 

- apps/obs-web/src/views/TripDetails.vue
- libs/bn-models/models/_lookups/fishery.ts
Fixed build errors for @toddhay-NOAA ,
* Object is possibly 'undefined'
* Make optional params for Fishery model
> Fix build errors: update Fishery Model, handle undefined case

- apps/obs-web/src/views/DebrieferTrips.vue
Update getSelectedString to receive the argument.
> Handle selected row update event

- libs/bn-auth/src/_services/auth.service.ts
Use server error message on login screen.
> Use server error

- apps/dev-auth-server/README.md
- apps/dev-auth-server/package-lock.json
- apps/dev-auth-server/package.json
- apps/dev-auth-server/src/main.ts
- apps/dev-auth-server/src/openapi.yaml
Available via https://localhost:9000/spec
> Add OpenAPI support to dev-auth-server

- apps/obs-wcgop-optecs/vue.config.js
- apps/obs-web/src/views/DebrieferTrips.vue
- apps/obs-web/vue.config.js
- libs/bn-models/models/_lookups/catch-grouping.ts
- libs/bn-models/models/_lookups/fishery.ts
- libs/bn-models/models/_lookups/taxonomy.ts
Fix build break in DebrieferView.vue, a bunch of tslint warnings on models, and added settings to update PWA earlier.
> Fix build break + PWA update

- apps/dev-auth-server/README.md
- apps/dev-auth-server/src/config/authProxyConfig.sample.json
- apps/dev-auth-server/src/openapi.yaml
- apps/dev-auth-server/src/routes/login.route.ts
- apps/dev-auth-server/src/routes/role.management.route.ts
- apps/dev-auth-server/src/routes/testauth.route.ts
- apps/dev-auth-server/src/util/roles_management.ts
- apps/obs-wcgop-optecs/src/_store/wcgop-app-state.module.ts
- apps/obs-web/src/_store/wcgop-app-state.module.ts
- libs/bn-auth/src/models/auth.model.ts
- libs/bn-models/models/_base/base.ts
- libs/bn-models/models/_common/boatnet-user.ts
- libs/bn-models/models/_common/brd-configuration.ts
- libs/bn-models/models/_common/index.ts
- libs/bn-models/models/_common/interaction-event.ts
- libs/bn-models/models/wcgop/wcgop-hlfc-configuration.ts
Covers dev-auth-server complete (prod pending) of #684
> Auth: Add application to RESTful API 

- apps/dev-auth-server/src/main.ts
- apps/dev-auth-server/src/openapi.yaml
- apps/dev-auth-server/src/routes/role.management.route.ts
- apps/dev-auth-server/src/util/roles_management.ts
Updated OpenAPI with newest additions for user-details
> dev-auth-server: Get/ Put user-details

- apps/obs-wcgop-optecs/src/views/Login.vue
- libs/bn-auth/src/_services/auth.service.ts
Added sample code to obs-wcgop-trips
> bn-auth-server: Expose apiUrl getter

- apps/obs-wcgop-optecs/src/views/Catch.vue
- libs/bn-pouch/src/_services/pouch.service.ts
- libs/bn-pouch/src/_store/pouch.module.ts
Allow progress bar creation, etc.
> bn-pouch: Add syncProgress to Vuex

- tools/couchdb/master-database/validation.json
Uses the members (under Permissions) to determine write access to the DB.
> couchdb: Add validation doc

- apps/ashop/package.json
- apps/ashop/src/_store/index.ts
- apps/ashop/src/assets/directional-buttons.css
- apps/ashop/src/data/data.ts
- apps/ashop/src/main.ts
- apps/ashop/src/views/TripDetails.vue
- apps/ashop/src/views/Trips.vue
- apps/obs-wcgop-optecs/package.json
- apps/obs-wcgop-optecs/src/_store/index.ts
- apps/obs-web/package.json
- apps/obs-web/src/_store/index.ts
- libs/bn-common/src/components/BoatnetDatetimePrime.vue
- libs/bn-common/src/components/BoatnetKeyboard.vue
- libs/bn-common/src/components/BoatnetKeyboardSelectList.vue
upgraded typescript version to work with composition api and changed from vuex-persist to vuexPersistance to work with the new typescript version and build successfully.
> getting composition syntax working in trip details page

- apps/ashop/src/data/data.ts
- apps/ashop/src/views/TripDetails.vue
- apps/ashop/src/views/Trips.vue
- libs/bn-common/src/components/BoatnetButtonToggleComp.vue
- libs/bn-common/src/components/BoatnetKeyboardSelectList.vue
- libs/bn-common/src/main.ts
- trip details now saving to the database
- added toggle button
- added cruise logic
> setting up trips page

- apps/ashop/src/router.ts
- apps/ashop/src/views/EndTrip.vue
- apps/ashop/src/views/Hauls.vue
- apps/ashop/src/views/TripDetails.vue
- libs/bn-common/src/components/BoatnetButtonToggleComp.vue
- libs/bn-common/src/components/BoatnetCommonInputComponent.vue
- libs/bn-common/src/components/BoatnetDatetimePrime.vue
- libs/bn-common/src/components/BoatnetKeyboardSelectList.vue
- libs/bn-common/src/components/BoatnetLicenses.vue
- libs/bn-common/src/components/BoatnetSummary.vue
https://github.com/nwfsc-fram/boatnet/issues/974 
Modified set in input elements to work for nested values. Also modified boatnet licenses to work for observers and add multiple observers to the program
> can now add multiple observers

- .eslintrc.js
- package.json
> Add ESLint configuration for boatnet

- apps/obs-wcgop-optecs/public/index.html
- apps/obs-wcgop-optecs/vue.config.js
> Update endpoint from observer-trips to boatnet

- apps/ashop/src/App.vue
- apps/ashop/src/views/EndTrip.vue
- apps/ashop/src/views/HaulDetails.vue
- apps/ashop/src/views/Hauls.vue
- apps/ashop/src/views/NonFishingDay.vue
- apps/ashop/src/views/TripDetails.vue
- apps/ashop/src/views/Trips.vue
- libs/bn-common/src/_store/keyboard.module.ts
- libs/bn-common/src/components/BoatnetCommonInputComponent.vue
- libs/bn-common/src/components/BoatnetDatetimePrime.vue
- libs/bn-common/src/components/BoatnetKeyboard.vue
- libs/bn-common/src/components/BoatnetKeyboardList.vue
- libs/bn-common/src/components/BoatnetKeyboardSelectList.vue
- libs/bn-common/src/components/BoatnetLicenses.vue
- libs/bn-common/src/components/BoatnetLocation.vue
-format changes: some text bars are too long, so shortened them
-fix console errors 
-add boatnet licenses back
-actually add a non-fishing day
> touch up changes

- apps/obs-web/src/assets/declarationsWorksheetVault.json
- apps/obs-web/src/layouts/Default.vue
- apps/obs-web/src/main.ts
- apps/obs-web/src/router.ts
- apps/obs-web/src/views/AddDeclaration.vue
- apps/obs-web/src/views/Declarations.vue
@sethgerou-noaa  I think there's a few things I want to do still before this goes into master, but opening the PR now so we can look at the diff of master in the meantime. My AddDeclarations file is too long so I need to split it out. Also would be really nice if I had the "one dropdown of all declarations" option/tab done before the user testing sessions.
At what point in the process do you usually merge your stuff from obs-web into master generally?  I think I will work on the couch DB integration into my stuff in a separate branch so we can still get this into master for user testing even if my DB stuff isn't into the production DB yet.
Oh, would also be good to get a code review at some point!
> WIP: Ole project

- apps/ashop/src/shims-vue.d.ts
- apps/ashop/src/views/HaulDetails.vue
- apps/ashop/src/views/Login.vue
- apps/obs-wcgop-optecs/src/shims-vue.d.ts
- libs/bn-common/package.json
- libs/bn-common/src/components/BoatnetCommonInputComponent.vue
- libs/bn-common/src/components/BoatnetKeyboard.vue
- libs/bn-common/src/components/BoatnetKeyboardList.vue
- libs/bn-common/src/components/BoatnetKeyboardSelectList.vue
- libs/bn-common/src/components/BoatnetLicenses.vue
- libs/bn-common/src/components/BoatnetLocation.vue
- libs/bn-common/src/shims-vue.d.ts
- libs/bn-common/src/views/BoatnetLogin.vue
- saving lookup Objs
- adding error message back to login screen
- modifying locations component to save both rawInputData and converted DD location.
> modifying location component and saving lookUps obj rather than just strings

- apps/obs-web/src/views/AddDeclaration.vue
Hey @sethgerou-noaa, this is the last bit I wanted to add before do the user testing session.  This commit adds the dropdown for the "chose and ID" toggle.
> adding new dropdown for OLE dec page

- apps/obs-wcgop-optecs/.eslintrc.js
- apps/obs-wcgop-optecs/package.json
- apps/obs-wcgop-optecs/src/App.vue
- apps/obs-wcgop-optecs/src/_store/tally.module.ts
- apps/obs-wcgop-optecs/src/components/OptecsBreadcrumbs.vue
- apps/obs-wcgop-optecs/src/components/tally/TallyAddExistingControls.vue
- apps/obs-wcgop-optecs/src/components/tally/TallyAddNewButton.vue
- apps/obs-wcgop-optecs/src/components/tally/TallyAllTalliesControls.vue
- apps/obs-wcgop-optecs/src/components/tally/TallyBtn.vue
- apps/obs-wcgop-optecs/src/components/tally/TallyControlBtn.vue
- apps/obs-wcgop-optecs/src/components/tally/TallyControls.vue
- apps/obs-wcgop-optecs/src/components/tally/TallyHistoryDialog.vue
- apps/obs-wcgop-optecs/src/components/tally/TallyLayoutControls.vue
- apps/obs-wcgop-optecs/src/components/tally/TallyPDFOptionsDialog.vue
- apps/obs-wcgop-optecs/src/components/tally/TallyTemplateManagerDialog.vue
- apps/obs-wcgop-optecs/src/components/tally/TallyWeightsForDialog.vue
- apps/obs-wcgop-optecs/src/layouts/Default.vue
- apps/obs-wcgop-optecs/src/views/Catch.vue
- apps/obs-wcgop-optecs/src/views/DynamicTripDetails.vue
- apps/obs-wcgop-optecs/src/views/HaulDetails.vue
- apps/obs-wcgop-optecs/src/views/Hauls.vue
- apps/obs-wcgop-optecs/src/views/Login.vue
- apps/obs-wcgop-optecs/src/views/Settings.vue
- apps/obs-wcgop-optecs/src/views/Tally.vue
- apps/obs-wcgop-optecs/src/views/TripDetails.vue
- apps/obs-wcgop-optecs/src/views/Trips.vue
Fix several hundred warnings and errors
> obs-wcgop-optecs: Fix lint errors uncovered by eslint

- apps/ashop/src/data/initHauls.ts
- apps/ashop/src/views/HaulDetails.vue
- apps/ashop/src/views/Hauls.vue
- libs/bn-common/src/components/BoatnetCommonInputComponent.vue
- libs/bn-common/src/components/BoatnetDatetime.vue
- libs/bn-common/src/components/BoatnetLocation.vue
- libs/bn-common/src/components/BoatnetTabPanel.vue
- updating computed  value, official total catch to MT
- breaking date time picker into two boxes so observers can type in time
- update non flow scale catch wt to toggle between kg and lbs
- updating format of haul details page so deployment and retrieval info is in two separate columns
> fixes based on wed ashop meeting

- apps/obs-web/src/assets/declarationsWorksheetVault.json
- apps/obs-web/src/views/AddDeclaration.vue
- apps/obs-web/src/views/Declarations.vue
And cleaning up logic for exemptions and other gear. This should be my last changes before user testing (famous last words).
> edits from OLE feedback 

- apps/obs-web/src/views/AddDeclaration.vue
@wsmith-nwfsc  and @sethgerou-noaa, here is the change Kate and Daniel wanted for the user testing session tomorrow morning. Lerna run build revealed a lot of warnings but in other files/apps. We would like to have this update in prod today so it can be used for the user testing, so not sure how to proceed? Should I spend some time trying to fix the warnings for the other files?
> adding temporary action for add to cart button for fishers testing

- apps/ashop/package.json
- apps/dev-auth-server/src/config/authProxyConfig.sample.json
- apps/dev-auth-server/src/routes/login.route.ts
- apps/obs-wcgop-optecs/src/views/Trips.vue
- apps/obs-web/package.json
- libs/bn-common/package.json
Adds initial dev-auth-server functionality to  #1326
> dev-auth-server: Add tripsApi

- apps/ashop/src/data/initHauls.ts
- apps/ashop/src/helpers/cruiseInfo.ts
- apps/ashop/src/layouts/Default.vue
- apps/ashop/src/views/HaulDetails.vue
- apps/ashop/src/views/Trips.vue
- libs/bn-common/src/_store/trips.module.ts
- libs/bn-common/src/_store/types/types.ts
- libs/bn-common/src/components/BoatnetCommonInputComponent.vue
- libs/bn-common/src/components/BoatnetLocation.vue
- adding rev to state to resolve issue where there were sometimes conflicting revisions. 
- saving dd longitude as negative 
- fixing locations to clear
- setting width of boatnet input components so they aren't super wide
- initializing lookups when logging in so they don't take forever to populate
https://github.com/nwfsc-fram/boatnet/issues/1311
> minor fixes

- apps/ashop/src/helpers/cruiseInfo.ts
- apps/ashop/src/views/Cruise.vue
- apps/ashop/src/views/Trips.vue
- apps/obs-web/src/views/AllTrips.vue
- apps/obs-web/src/views/EMDataCompare.vue
- apps/obs-web/src/views/EMRateManagement.vue
- apps/obs-web/src/views/EMTaskManagement.vue
- apps/obs-web/src/views/TripDetails.vue
- libs/bn-common/src/helpers/trips-api.ts
- libs/bn-common/src/main.ts
- moved trips-api client into the bn-commons folder
- modified obs-web components to reference trips-api in new location
> calling new cruiseAPI when navigating to trips page

- apps/obs-web/package.json
- apps/obs-web/src/_store/debriefer.module.ts
- apps/obs-web/src/_store/types/types.ts
- apps/obs-web/src/layouts/Default.vue
- apps/obs-web/src/main.ts
- apps/obs-web/src/shims-vue.d.ts
- apps/obs-web/src/views/DebrieferData.vue
- apps/obs-web/src/views/DebrieferDialog.vue
- apps/obs-web/src/views/DebrieferErrors.vue
- apps/obs-web/src/views/DebrieferLayout.vue
- apps/obs-web/src/views/DebrieferTrips.vue
- apps/obs-web/src/views/PrimeTable.vue
Setting up wcgop debriefer tool. In this PR populated observers and evaluation period drop downs by querying couch and showing hte appropriate trips based on your filter criteria. 
Also separated data and error tab
> Wcgop Debriefer tool partially working

- apps/obs-web/src/_store/debriefer.module.ts
- apps/obs-web/src/_store/types/types.ts
- apps/obs-web/src/helpers/localStorage.ts
- apps/obs-web/src/main.ts
- apps/obs-web/src/views/DebrieferAshopData.vue
- apps/obs-web/src/views/DebrieferCatchBaskets.vue
- apps/obs-web/src/views/DebrieferCatchSpecies.vue
- apps/obs-web/src/views/DebrieferCatchSpecimens.vue
- apps/obs-web/src/views/DebrieferCatches.vue
- apps/obs-web/src/views/DebrieferErrors.vue
- apps/obs-web/src/views/DebrieferLayout.vue
- apps/obs-web/src/views/DebrieferOperations.vue
- apps/obs-web/src/views/DebrieferTrips.vue
- apps/obs-web/src/views/DebrieferWcgopData.vue
- apps/obs-web/src/views/PrimeTable.vue
- libs/bn-common/package-lock.json
- makes display columns sticky
- filtering
- added haul info
> debriefer table updates

- apps/obs-web/src/views/AddDeclaration.vue
- apps/obs-web/src/views/DeclarationCart.vue
- apps/obs-web/src/views/Declarations.vue
- added table option.
- now makes oleVessel couch docs if they are missing.
- Slightly different views if OLE staff role
> Updates to dec pag

- apps/obs-web/package.json
- apps/obs-web/src/assets/declarationsWorksheetVault.json
- apps/obs-web/src/layouts/Default.vue
- apps/obs-web/src/router.ts
- apps/obs-web/src/views/AddDeclaration.vue
- apps/obs-web/src/views/Declarations.vue
- apps/obs-web/src/views/Home.vue
- apps/obs-web/src/views/OLEEFPManagement.vue
- libs/bn-common/package.json
updates to bn-models published, and seems to build fine locally....
Can I get a quick review @wsmith-nwfsc or @sethgerou-noaa? In the spirit of trying to do more code reivews...
> Ole staff pages

- apps/obs-web/src/views/Trips.vue
if confirmed dates have not been selected.
#1701
> obs-web: trip close button warn +return

- apps/obs-web/src/views/EMRateManagement.vue
- apps/obs-web/src/views/OTSManagement.vue
- apps/obs-web/src/views/OtsTripHistory.vue
- apps/obs-web/src/views/OtsTrips.vue
- apps/obs-web/src/views/TripDetails.vue
- apps/obs-web/src/views/Trips.vue
single watcher to update changeLog for activeTrip
> obs-web: #1707

- apps/obs-web/src/views/Declarations.vue
Fixing alert notification I was using. I stopped logging for now. There is a slight bug that I sort of fixed, but still a non-breaking kink i need to work out eventually. This is part of #1692.
> fixing error message bug mentioned in Eric's testing.

- apps/obs-web/service-worker.js
- apps/obs-web/src/views/TripDetails.vue
- apps/obs-web/src/views/Trips.vue
Trip calendar select next month dates #1614
> Trip calendar select next month dates #1614

- apps/obs-web/service-worker.js
- apps/obs-web/src/layouts/Default.vue
- apps/obs-web/src/router.ts
- apps/obs-web/src/views/Home.vue
- apps/obs-web/src/views/LogMissingTrip.vue
- apps/obs-web/src/views/MissedTripLog.vue
- apps/obs-web/src/views/OtsTrips.vue
- apps/obs-web/src/views/TripDetails.vue
- apps/obs-web/src/views/Trips.vue
#1736 - create missed trips log
#1737 - 48hr warning calculated and thrown based on time selection
#1704 - add missing image icon and x number of closed trips missing an image warning
test: ots trips global search shaded differently (to stand out from background) #1724
#1738 - port selection search/filter
> obs-web: misc

- apps/obs-web/service-worker.js
- apps/obs-web/src/views/AllTrips.vue
- apps/obs-web/src/views/OtsTrips.vue
- move created fileds to end on All Trips and Ots Trips.
> obs-web: #1752 - add created date to All Trips

- apps/obs-web/src/views/TripDetails.vue
fix mobile clear on focus issue
> obs-web: #1742 - make ports clearable /

- apps/obs-web/service-worker.js
- apps/obs-web/src/components/FileUploader.vue
- apps/obs-web/src/views/ELogbook.vue
- apps/obs-web/src/views/LogMissingTrip.vue
- apps/obs-web/src/views/TripDetails.vue
- apps/obs-web/src/views/Trips.vue
- libs/bn-common/src/helpers/trips-api.ts
on trips page - for EM providers #1718
other misc fixes.
> obs-web: 'enter logbook data' button

- apps/obs-wcgop-optecs/src/views/DynamicTripDetails.vue
- apps/obs-web/src/components/FileUploader.vue
- apps/obs-web/src/router.ts
- apps/obs-web/src/views/LogMissingTrip.vue
- apps/obs-web/src/views/TripDetails.vue
- apps/obs-web/src/views/Trips.vue
- libs/bn-common/src/components/BoatnetDatetimePrime.vue
also #1782, #1778, #1777, and #1775
> obs-web: #1774 trip depart and return dates in separate fields.

- libs/bn-common/src/helpers/trips-api.ts
> Get apiURL via function instead of potential race condition const

- apps/obs-web/src/components/FileUploader.vue
- apps/obs-web/src/views/ELogbook.vue
- apps/obs-web/src/views/Home.vue
- apps/obs-web/src/views/LogMissingTrip.vue
- apps/obs-web/src/views/TripDetails.vue
- apps/obs-web/src/views/Trips.vue
#1831, #1821, #1823, #1824, #1825, #1827, #1828, #1822, #1826
> ots/em: misc bug fixes and features

- apps/obs-web/src/App.vue
- apps/obs-web/src/layouts/Default.vue
- apps/obs-web/src/views/LogMissingTrip.vue
- apps/obs-web/src/views/TripDetails.vue
not sticking on moblie (#1905)
> obs-web: fix missing trip port selection

- apps/obs-web/src/views/ELogbook.vue
- apps/obs-web/src/views/EMApiPortal.vue
- apps/obs-web/src/views/EMDataCompare.vue
- apps/obs-web/src/views/EmExpansions.vue
logbook use em taxonomy-aliases
> em: update comparisson screen (#1855)

- apps/obs-web/package.json
- apps/obs-web/src/main.ts
- apps/obs-web/src/router.ts
- apps/obs-web/src/views/EMApiPortal.vue
- apps/obs-web/src/views/EMReview.vue
- apps/obs-web/src/views/ViewImage.vue
https://github.com/nwfsc-fram/boatnet/issues/1970
https://github.com/nwfsc-fram/boatnet/issues/1971
> Adding screenshot and errors table

- apps/obs-web/src/_store/types/types.ts
- apps/obs-web/src/_store/user.module.ts
- apps/obs-web/src/layouts/Default.vue
- apps/obs-web/src/views/EMDataCompare.vue
- apps/obs-web/src/views/Home.vue
- apps/obs-web/src/views/UserDetails.vue
… in user config #1976, compare screen (item 3) of #2007
> obs-web: - auto-collapse side menu 

- apps/obs-web/src/views/EMDataCompare.vue
- apps/obs-web/src/views/EMTaskManagement.vue
#2021 (Task Mgmt - show revision count)
> EM: #2020 (comparison screen species code error)

- apps/obs-web/src/views/TripsApiInterface.vue
> tripsApiInterface update port options

- .gitignore
- apps/obs-web/src/layouts/Default.vue
- apps/obs-web/src/views/ELogbook.vue
- apps/obs-web/src/views/EMResults.vue
comments and calcWeightType cols
> em results back button,

- apps/obs-web/src/helpers/getFields.ts
- apps/obs-web/src/views/DebrieferCatches.vue
- apps/obs-web/src/views/DebrieferTrips.vue
- libs/bn-common/src/components/BoatnetTreeTable.vue
Addressing the debriefer finding issues listed here 
https://docs.google.com/spreadsheets/d/1GeyW494YI9TmSYO3QFtyKjQ_Ka5IP6NxQKkaArvvwoE/edit#gid=0
Adding missing columns to trips page
- USCG#
-State Regulation #
Enable searching by observer only on evaluation page 
Catch changes 
- Fixed table formatting 
- Eliminate pagination
- Added sex and viability 
- Shifted columns to desired order
> General debriefer tool fixes

- apps/obs-web/src/_store/debriefer.module.ts
- apps/obs-web/src/_store/types/types.ts
- apps/obs-web/src/views/AttributeSearchComp.vue
- apps/obs-web/src/views/DebrieferErrors.vue
- apps/obs-web/src/views/PrimeTable.vue
- apps/obs-web/src/views/Trips2pt0.vue
populate errors table from errors docs #2161
EM: Remove max and optimized retention question for MSCV vessels #2138
> Debriefer:

- apps/obs-web/src/helpers/getFields.ts
- apps/obs-web/src/views/DebrieferLayout.vue
Also fixing a bug that was showing empty entries when searching by observer
> Added a way to minimize search and evaluation box

- apps/obs-web/src/views/DebrieferCatches.vue
- apps/obs-web/src/views/DebrieferErrors.vue
- apps/obs-web/src/views/PrimeTable.vue
https://github.com/nwfsc-fram/boatnet/issues/2152
> toggle columns for hauls from trawl to fixed gear

- apps/obs-web/src/layouts/Default.vue
- apps/obs-web/src/router.ts
- apps/obs-web/src/views/AttributeSearchComp.vue
- apps/obs-web/src/views/DebrieferErrors.vue
- apps/obs-web/src/views/ELogbook.vue
- apps/obs-web/src/views/ErrorManagement.vue
- apps/obs-web/src/views/TripDetails2.vue
Add tripId to search attributes (#2183)
Handle invalid net type in e-logbook (#2121)
initial error management page (#2171)
ots - remove retention question for mscv (@2183)
progress on updated trips page (#2136)
> debriefer / EM / OTS

- apps/ashop/package.json
- apps/obs-wcgop-optecs/package.json
- apps/obs-web/package.json
- apps/obs-web/src/views/TripDetails.vue
tweak alerts on trip details,
update bn-models version
#2229, #2230
> ots: correctly designate missed trips,

- apps/obs-web/src/assets/logbookExample.json
- apps/obs-web/src/views/DebrieferAssessment.vue
- apps/obs-web/src/views/ELogbook.vue
populate otc sampling procedures and catch categories based on operations. Update per new spreadsheet.
> obs-web: Debriefer Assessment #2266

- apps/obs-web/src/_store/debriefer.module.ts
- apps/obs-web/src/views/DebrieferWcgopData.vue
- apps/obs-web/src/views/DebrieferWcgopEvaluation.vue
- apps/obs-web/src/views/Home.vue
- apps/obs-web/src/views/PrimeTable.vue
- apps/obs-web/src/views/UserDetails.vue
Storing user's program and display codes settings
> storing user settings in state and the db

- apps/obs-web/src/views/DebrieferSelectComp.vue
- apps/obs-web/src/views/RackBiospecimens.vue
https://github.com/nwfsc-fram/boatnet/issues/2076
> adding rack bios page

- apps/obs-web/vue.config.js
Change has no effect running locally - Once approved/merged, I'll test on DEV first then request another qualys scan.
> Add xframe deny header

- libs/bn-common/src/helpers/trips-api.ts
mongoAggregate, mongoGetOne, mongoGetMany
> obs-web: updated mongoRead helper, and added:

- apps/obs-web/src/views/AddDeclaration.vue
- apps/obs-web/src/views/DeclarationCart.vue
- apps/obs-web/src/views/Declarations.vue
olevessel load support state reg num
> declarations: display vms declarations +
